### ISSUE TITLE
Documentation seems very inconsistant.

### ISSUE THREAD

**Issue by carlkesselman** [informatics-isi-edu/mesh-viewer#45]
I am trying to use this application, and finding the documentation pretty confusing.  Some of the issues:

It says that a valid property is model_id and model_caption. Yet the example has id and label as its properties. The example includes a RID as a property, yet the model spec doesn’t have RID.  The spec has a property model_unitconversion, yet the example has unit_conversion.  The example includes properties that are not in the model specification, such as rotate and volume.

The Mesh spec has a RID field, which it say is the ID of the mesh, which is inconsistent with the previous use of the term ID. Not clear what the purpose of link object is.  We already have the url for the object, couldn't we just include the label as a separate field, as it actually appears in the example.  

Landmark also includes RID. and in landmark, it says there is a mesh field, which is the ID of the mesh, which the example shows is clearly a RID.  Why isn't this given a more meaningful name like MESH_RID if that is what is intended. The landmark spec has a location, which is supposed to be named url, which is a string, but the landmark example has point_x, point_y, and point_z to indicate location.   Of all of the properties in the spec, the only one that is indicated as optional is the anatomy_id in landmark and mesh.  Does this mean all of the other properties are required?

**Comment by robes** [comment]
Let's go back to what was specified originally:
https://github.com/informatics-isi-edu/mesh-viewer/issues/37#issuecomment-441821650

I'm going to update the model link and repeat the rest of them. The model link is updated only so that I don't use the `*` which fetched some unused attributes, so I changed that link here to specify just what was needed.

model:
https://dev.facebase.org/ermrest/catalog/1/attribute/viz:model/RID=1-43KT/RID,label,description,bg_color_r,bg_color_g,bg_color_b,bounding_box_color_r,bounding_box_color_b,bounding_box_color_g,show_bounding_box,unit_conversion

mesh:
https://dev.facebase.org/ermrest/catalog/1/attribute/viz:model/RID=1-43KT/model_mesh:=viz:model_mesh_data/mesh:=mesh_data/anatomy:=left(mesh:anatomy)/$mesh/RID,url,filename,label,description,color_r:=model_mesh:color_r,color_g:=model_mesh:color_g,color_b:=model_mesh:color_b,opacity:=model_mesh:opacity,anatomy:=anatomy:name,anatomy_id:=anatomy:RID

landmark:
https://dev.facebase.org/ermrest/catalog/1/attribute/viz:model/RID=1-43KT/model_mesh:=viz:model_mesh_data/mesh:=mesh_data/L:=viz:landmark/anatomy:=left(anatomy)/$L/RID,mesh,label,description,point_x,point_y,point_z,radius,color_r,color_g,color_b,anatomy:=anatomy:name,anatomy_id:=anatomy:RID

**Comment by robes** [comment]
@carlkesselman please check out the links above in my comment. I don't want to go changing these and forcing facebase to make updates to a new spec. Nick should document these correctly and then you can make your deployment emit these and all should work out.

**Comment by NickolausDS** [comment]
@robes Changes are up at #46. Let me know if anything is inaccurate.

**Comment by robes** [comment]
i believe this has been addressed. if we find new doc issues we can open specific issues.
